export const LOAD_CATEGORIES = 'LOAD_CATEGORIES';
export const ACTIVE_CATEGORY = 'ACTIVE_CATEGORY';

export const LOAD_POSTS = 'LOAD_POSTS';
export const LOAD_SINGLE_POST = 'LOAD_SINGLE_POST';
export const ADD_POST = 'ADD_POST';
export const UPDATE_POST = 'UPDATE_POST';
export const DELETE_POST = 'DELETE_POST';
export const SORT_POSTS = 'SORT_POSTS';

export const VOTE = 'VOTE';
export const UPDATE_POST_VOTE = 'UPDATE_POST_VOTE';
export const UPDATE_COMMENT_VOTE = 'UPDATE_COMMENT_VOTE';

export const LOAD_COMMENTS = 'LOAD_COMMENTS';
export const ADD_COMMENT = 'ADD_COMMENT';
export const UPDATE_COMMENT = 'UPDATE_COMMENT';
export const DELETE_COMMENT = 'DELETE_COMMENT';
